trigger:
  branches:
    include:
    - main
resources:
  repositories:
  - repository: self
    type: git
    ref: main
jobs:
- job: Main
  displayName: build and push
  pool:
    vmImage: ubuntu-20.04
  steps:
  - checkout: self
    clean: true
  - task: DockerInstaller@0
    displayName: Install Docker
    inputs:
      dockerVersion: 20.10.11
      releaseType: stable
  - task: Docker@2
    displayName: BuildAndPush
    inputs:
      containerRegistry: 431f8689-26bb-4f69-a9b3-aeb8982ee1ae
      repository: miqm/bicep-cli
      Dockerfile: Dockerfile
      tags: |
        $(Build.BuildNumber)
        latest
      addPipelineData: false
      addBaseImageData: false
...
