trigger:
  batch: true
  branches:
    include:
      - main
  tags:
    include:
      - v*
  paths:
    include:
      - Dockerfile
      - .ci/bicep-cli.yml

pr:
  autoCancel: true
  branches:
    include:
      - main
  paths:
    include:
      - Dockerfile
      - .ci/bicep-cli.yml
  drafts: false

resources:
  repositories:
    - repository: self
      type: git
      ref: main

jobs:
  - job: Main
    strategy:
      matrix:
        Python3_10_bookworm:
          PYTHON_VERSION: "3.10.14-slim-bookworm"
          PYTHON_TAG: "python3.10-bookworm"
          PYTHON_TAG2: "python3.10"
          LATEST: ""
        Python3_10_bullseye:
          PYTHON_VERSION: "3.10.14-slim-bullseye"
          PYTHON_TAG: "python3.10-bullseye"
          PYTHON_TAG2: ""
          LATEST: ""
        Python3_11_bookworm:
          PYTHON_VERSION: "3.11.9-slim-bookworm"
          PYTHON_TAG: "python3.11-bookworm"
          PYTHON_TAG2: "python3.11"
          LATEST: ""
        Python3_11_bullseye:
          PYTHON_VERSION: "3.11.9-slim-bullseye"
          PYTHON_TAG: "python3.11-bullseye"
          PYTHON_TAG2: ""
          LATEST: ""
        Python3_12_bookworm:
          PYTHON_VERSION: "3.12.4-slim-bookworm"
          PYTHON_TAG: "python3.12-bookworm"
          PYTHON_TAG2: "python3.12"
          LATEST: "latest"
        Python3_12_bullseye:
          PYTHON_VERSION: "3.12.4-slim-bullseye"
          PYTHON_TAG: "python3.12-bullseye"
          PYTHON_TAG2: ""
          LATEST: ""
    ${{ if startsWith(variables['Build.SourceBranch'], 'refs/tags/v') }}:
      displayName: Publish
    ${{ else }}:
      displayName: Build
    pool:
      vmImage: ubuntu-20.04
    steps:
      - checkout: self
        clean: true
      - task: DockerInstaller@0
        displayName: Install Docker
        inputs:
          dockerVersion: 24.0.6
          releaseType: stable
      - ${{ if startsWith(variables['Build.SourceBranch'], 'refs/tags/v') }}:
        - script: |
            echo "##vso[task.setvariable variable=VERSION1]$(echo "$(Build.SourceBranchName)" | cut -d '.' -f 1-2)"
            echo "##vso[task.setvariable variable=VERSION2]$(echo "$(Build.SourceBranchName)" | cut -d '.' -f 1-3)"
            echo "##vso[task.setvariable variable=VERSION3]$(Build.SourceBranchName)"
          displayName: Set versions
      - ${{ else }}:
        - script: |
            echo "##vso[task.setvariable variable=VERSION1]0.0"
            echo "##vso[task.setvariable variable=VERSION2]0.0.0"
            echo "##vso[task.setvariable variable=VERSION3]0.0.0.0"
          displayName: Set versions
      - script: |
          echo "##vso[task.setvariable variable=tag0_1]$(PYTHON_TAG)"
          echo "##vso[task.setvariable variable=tag1_1]$(VERSION1)-$(PYTHON_TAG)"
          echo "##vso[task.setvariable variable=tag2_1]$(VERSION2)-$(PYTHON_TAG)"
          echo "##vso[task.setvariable variable=tag3_1]$(VERSION3)-$(PYTHON_TAG)"
          echo "##vso[task.setvariable variable=tag0_2]"
          echo "##vso[task.setvariable variable=tag1_2]"
          echo "##vso[task.setvariable variable=tag2_2]"
          echo "##vso[task.setvariable variable=tag3_2]"
          echo "##vso[task.setvariable variable=tag0_3]"
          echo "##vso[task.setvariable variable=tag1_3]"
          echo "##vso[task.setvariable variable=tag2_3]"
          echo "##vso[task.setvariable variable=tag3_3]"
        displayName: Set tags 1
      - script: |
          echo "##vso[task.setvariable variable=tag0_2]$(PYTHON_TAG2)"
          echo "##vso[task.setvariable variable=tag1_2]$(VERSION1)-$(PYTHON_TAG2)"
          echo "##vso[task.setvariable variable=tag2_2]$(VERSION2)-$(PYTHON_TAG2)"
          echo "##vso[task.setvariable variable=tag3_2]$(VERSION3)-$(PYTHON_TAG2)"
        displayName: Set tags 2
        condition: ne(variables['PYTHON_TAG2'], '')
      - script: |
          echo "##vso[task.setvariable variable=tag0_3]latest"
          echo "##vso[task.setvariable variable=tag1_3]$(VERSION1)"
          echo "##vso[task.setvariable variable=tag2_3]$(VERSION2)"
          echo "##vso[task.setvariable variable=tag3_3]$(VERSION3)"
        displayName: Set tags 3
        condition: ne(variables['LATEST'], '')
      - ${{ if startsWith(variables['Build.SourceBranch'], 'refs/tags/v') }}:
          - task: Docker@2
            displayName: Build and Push
            inputs:
              command: buildAndPush
              containerRegistry: 431f8689-26bb-4f69-a9b3-aeb8982ee1ae
              repository: miqm/bicep-cli
              Dockerfile: Dockerfile
              arguments: --build-arg PYTHON_VERSION=$(PYTHON_VERSION)
              tags: |
                $(tag0_1)
                $(tag1_1)
                $(tag2_1)
                $(tag3_1)
                $(tag0_2)
                $(tag1_2)
                $(tag2_2)
                $(tag3_2)
                $(tag0_3)
                $(tag1_3)
                $(tag2_3)
                $(tag3_3)
              addPipelineData: false
              addBaseImageData: false
      - ${{ else }}:
          - task: Docker@2
            displayName: Build
            inputs:
              command: build
              containerRegistry: 431f8689-26bb-4f69-a9b3-aeb8982ee1ae
              repository: miqm/bicep-cli
              Dockerfile: Dockerfile
              arguments: --build-arg PYTHON_VERSION=$(PYTHON_VERSION)
              tags: |
                $(tag0_1)
                $(tag1_1)
                $(tag2_1)
                $(tag3_1)
                $(tag0_2)
                $(tag1_2)
                $(tag2_2)
                $(tag3_2)
                $(tag0_3)
                $(tag1_3)
                $(tag2_3)
                $(tag3_3)
              addPipelineData: false
              addBaseImageData: false
