name: Dependabot update Dockerfile
on:
  pull_request_target:
    types: [synchronize]
    branches:
      - main
    paths:
      - ".github/workflows/dependabot_hack.yml"
jobs:
  updateDockerfile:
    if: ${{ github.actor == 'dependabot[bot]' }}
    name: UpdateDockerfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10.8"
      - name: run updateDockerfile.py
        run: |
          pip install -r requirements.txt  
          python updateDockerfile.py
      - name: commit changes to Dockerfile
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           FILE_TO_COMMIT: Dockerfile
           DESTINATION_BRANCH: ${{ github.head_ref }}
        run: |
          git add .
          if ! git diff-index --quiet HEAD --; then
            export MESSAGE="Update $FILE_TO_COMMIT"
            export SHA=$( git rev-parse $DESTINATION_BRANCH:$FILE_TO_COMMIT )
            export CONTENT=$( base64 -i $FILE_TO_COMMIT )
            gh api --method PUT /repos/:owner/:repo/contents/$FILE_TO_COMMIT \
              --field message="$MESSAGE" \
              --field content="$CONTENT" \
              --field encoding="base64" \
              --field branch="$DESTINATION_BRANCH" \
              --field sha="$SHA"
          fi
